### ISSUE TITLE
v0.0.2.9 : NoneType' object is not iterable

### ISSUE THREAD

**Issue by farhanito** [RenierM26/ha-ezviz#22]
I'm getting this error

> bash-5.0# pyezviz -u user -p pass -r sgp devices status
'NoneType' object is not iterable

**Comment by RenierM26** [comment]
Hi @farhanito,

Could you please try again with the latest release?

**Comment by farhanito** [comment]
Thanks @RenierM26 

Still the same issue though

> CoreELEC (official): 9.2.0 (Amlogic-ng.arm)
CoreELEC:~ # docker exec -it homeassistant /bin/bash
bash-5.0# pyezviz -u xxxxxx -p xxxxxx -r sgp devices status
'NoneType' object is not iterable
bash-5.0# pip list | grep pyezviz
pyezviz                          0.1.6.6
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
bash-5.0#

Here's the log from HA

> Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:31
Integration: Ezviz (documentation)
First occurred: 18:09:20 (194 occurrences)
Last logged: 22:40:50

> Unexpected error fetching ezviz_cloud data: 'NoneType' object is not iterable

> Traceback (most recent call last):

>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh

    self.data = await self._async_update_data()

>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data

    return await self.hass.async_add_executor_job(self._update_data)

>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data

    cameras = self.ezviz_client.load_cameras()

>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 303, in load_cameras

    camera.load()

>   File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 35, in load

    self.switch_status()

>   File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 39, in switch_status

    for switch in self._device.get("switchStatusInfos"):

> TypeError: 'NoneType' object is not iterable

**Comment by RenierM26** [comment]
@farhanito,

Think I found the issue and have implemented a fix for devices that don't report switch statuses. Could you please test 0.0.3.1 (Latest release)?

**Comment by farhanito** [comment]
I'm getting this error now

> Logger: custom_components.ezviz_cloud.coordinator
> Source: custom_components/ezviz_cloud/coordinator.py:31
> Integration: Ezviz (documentation)
> First occurred: 1:10:35 (3 occurrences)
> Last logged: 1:10:59
> 
> Unexpected error fetching ezviz_cloud data: 'NoneType' object has no attribute 'get'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
>     return await self.hass.async_add_executor_job(self._update_data)
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
>     cameras = self.ezviz_client.load_cameras()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 352, in load_cameras
>     cameras.append(camera.status())
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 134, in status
>     "local_ip": self._device.get("wifiInfos", {}).get("address", "0.0.0.0"),
> AttributeError: 'NoneType' object has no attribute 'get'
>

**Comment by RenierM26** [comment]
Hi @farhanito,

This should now work in the latest version. Could you please test? v0.0.3.2

**Comment by farhanito** [comment]
Still not working

> Logger: custom_components.ezviz_cloud.coordinator
> Source: custom_components/ezviz_cloud/coordinator.py:31
> Integration: Ezviz (documentation)
> First occurred: 6:18:57 (1 occurrences)
> Last logged: 6:18:57
> 
> Unexpected error fetching ezviz_cloud data: 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
>     return await self.hass.async_add_executor_job(self._update_data)
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
>     cameras = self.ezviz_client.load_cameras()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 352, in load_cameras
>     cameras.append(camera.status())
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 140, in status
>     "detection_sensibility": self.detection_sensibility(),
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 60, in detection_sensibility
>     result = self._client.get_detection_sensibility(self._serial)
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 729, in get_detection_sensibility
>     for idx in response_json["algorithmConfig"]["algorithmList"]:
> TypeError: 'NoneType' object is not iterable

**Comment by RenierM26** [comment]
HI @farhanito,

It might be the NVR that causes issues. Thank you for your patience with all the tests, your're really helping in building resilience against a lot of unknowns.

I have added in a check under the detection sensibility method. It should fix this issue.

Mind testing the latest release? v0.0.3.3 I think we're almost there, there could be another failure under the alarm check but shouldn't be. (Basically the next and last "complex" query)

**Comment by farhanito** [comment]
Hi @RenierM26 
No worries, i should be the one to thank you..

Ok, now.. with v0.0.3.3, all my devices get populated correctly. Even the NVR. Yay! 
So many entities 🙄 

I currently only have one them set up in config yaml. But when i tried to see the stream, it failed with this errors
(both local or remote viewing)

> Logger: libav.tcp
> Source: components/stream/worker.py:79
> First occurred: 20:00:34 (2 occurrences)
> Last logged: 20:00:34
> 
> Connection to tcp://0.0.0.0:554?timeout=5000000 failed: Connection refused

> Logger: homeassistant.components.stream.worker
> Source: components/stream/worker.py:83
> Integration: Stream (documentation, issues)
> First occurred: 20:00:34 (2 occurrences)
> Last logged: 20:00:34
> 
> Error opening stream rtsp://admin:XXXXXXX@0.0.0.0:554/H.264

Config yaml

> stream:
> ffmpeg:
> camera:
> 
> ezviz_cloud:
>     cameras:
>         D87105772:
>             username: admin
>             password: XXXXXXX

So close now.. excellent job!

**Comment by raffaelevall** [comment]
Sorry if I insert myself in the speech and congratulations for the great work @ RenierM26.

I have a C6N, integration is successful but when I try to see the flow I always get the error:

`Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:83
Integration: Stream (documentation, issues)
First occurred: 23:17:30 (10 occurrences)
Last logged: 23:38:34

Error opening stream rtsp://admin:XXXXXX@0.0.0.0:554`

is it correct that IP 0.0.0.0 is reported and not the correct one of the cam?
many tks

**Comment by farhanito** [comment]
I just saw an update from HACS.
Camera feed is working now! Nice.

Thanks @RenierM26

**Comment by raffaelevall** [comment]
After the update i still have the problem.
If I put the rtsp://admin: XXXXXX@0.0.0.0:554 with the correct IP of the cam in VLC everything works.
tks again @RenierM26

**Comment by RenierM26** [comment]
Hi @farhanito ,

The latest version should fix the "missing ip" problem. The api seems to have a bug with some of the c6 cameras where the ip disappears from connection infos but it remains under wifi infos.

@raffaelevall ,

Have you tried the latest version released yesterday?

**Comment by farhanito** [comment]
Confirmed. All my cameras are working now.

Thanks @RenierM26

**Comment by raffaelevall** [comment]
Hi @RenierM26, 
I try but nothing change 😢. 
`
2021-02-20 09:51:19 ERROR (stream_worker) [libav.tcp] Connection to tcp://0.0.0.0:554?timeout=5000000 failed: Connection refused
2021-02-20 09:51:19 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://admin:XXXXXX@0.0.0.0:554
`

**Comment by farhanito** [comment]
What's your camera model @raffaelevall ?
Have you disable "image encryption" option?

**Comment by raffaelevall** [comment]
@farhanito the camera model is C6N and I disable the encryption of the image in the app, but I have the error. 
I have to try to restart the cam when I will go home

**Comment by raffaelevall** [comment]
Hi  @RenierM26
with the new 4.2 version the local ip is always not correct but the RTSP stream address disappeared:
`local_ip: 0.0.0.0
RTSP stream: ''`

**Comment by RenierM26** [comment]
Hi @raffaelevall,

It looks like the normal endpoint aren't returning an ip. Could you perhaps send me  your pagelist? The page only works on IE or Safari.

The RSTP attribute is still in the code, just looks like hassio doesn't display it. I'll add it as a sensor in the next release.

Just change the region code in the second url. (eu = European server) 

1) Login here:
https://i.ezvizlife.com/

2) Then open this url:
https://apiieu.ezvizlife.com/v3/userdevices/v1/resources/pagelist?groupId=-1&limit=30&offset=0&filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CNODISTURB%2CKMS%2CP2P%2CTIME_PLAN%2CCHANNEL%2CVTM%2CDETECTOR%2CFEATURE%2CUPGRADE%2CVIDEO_QUALITY%2CQOS

The second link will download a json file with your camera setting. I should be able to find the IP in the output and then I can incorporate it in the API.

**Comment by raffaelevall** [comment]
> Hi @raffaelevall,
> 
> It looks like the normal endpoint aren't returning an ip. Could you perhaps send me your pagelist? The page only works on IE or Safari.
> 
> The RSTP attribute is still in the code, just looks like hassio doesn't display it. I'll add it as a sensor in the next release.
> 
> Just change the region code in the second url. (eu = European server)
> 
> 1. Login here:
>    https://i.ezvizlife.com/
> 2. Then open this url:
>    https://apiieu.ezvizlife.com/v3/userdevices/v1/resources/pagelist?groupId=-1&limit=30&offset=0&filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CNODISTURB%2CKMS%2CP2P%2CTIME_PLAN%2CCHANNEL%2CVTM%2CDETECTOR%2CFEATURE%2CUPGRADE%2CVIDEO_QUALITY%2CQOS
> 
> The second link will download a json file with your camera setting. I should be able to find the IP in the output and then I can incorporate it in the API.

Hi @RenierM26,
I download the json file, the local ip is there

`{"domain":"vtmtxeu.ezvizlife.com","externalIp":"XX.XX.XX.91","internalIp":null,"port":10554,"forceStreamType":0,"isBackup":0}},"P2P":{"XXXXXX999":[{"ip":"XX.XX.XX.145","port":6000},{"ip":"XX.XX.XX.84","port":6000}]},"CONNECTION":{"XXXXXX999":{"localIp":"192.168.1.106","netIp":"XXX.XXX.XXX.XXX","localRtspPort":0,"netRtspPort":0,"localCmdPort":9010,"netCmdPort":35996,"localStreamPort":9020,"netHttpPort":0,"localHttpPort":0,"netStreamPort":35634,"netType":3,"wanIp":null,"upnp":false}},"KMS":{"XXXXXX999":{"secretKey":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","version":"101"}},"STATUS":{"XXXXXX999":`

Tell me if you need the entire file and how to send it to you.
tks again
